// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: qYXJkyifyxfQuqtTDFQCRa
// Component: sRwVN1JpEF
import * as React from "react";
import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/react-web/lib/host";
import {
  hasVariant,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import Navbar from "../../Navbar"; // plasmic-import: klxX5nKFAD/component
import Button2 from "../../Button2"; // plasmic-import: VS4Cm-DCBjr/component
import Footer from "../../Footer"; // plasmic-import: cdtIcE32qk/component
import { useScreenVariants as useScreenVariantstvKzUvB7Ggzh0 } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: tvKzUvB7GGZH0/globalVariant
import "@plasmicapp/react-web/lib/plasmic.css";
import plasmic_antd_5_hostless_css from "../antd_5_hostless/plasmic_antd_5_hostless.module.css"; // plasmic-import: ohDidvG9XsCeFumugENU3J/projectcss
import projectcss from "./plasmic_tiny_garden_solutions.module.css"; // plasmic-import: qYXJkyifyxfQuqtTDFQCRa/projectcss
import sty from "./PlasmicBlogOverview.module.css"; // plasmic-import: sRwVN1JpEF/css
import ChecksvgIcon from "./icons/PlasmicIcon__Checksvg"; // plasmic-import: K_9f4twbCGN/icon
import Icon6Icon from "./icons/PlasmicIcon__Icon6"; // plasmic-import: 6jcESFctCjp/icon
import image7YoXd0XTyBq from "./images/image7.jpg"; // plasmic-import: yoXd0xTy_bq/picture
import pexelsWasharapolDBinyoJundang2731667JpgQtUvhAbg from "./images/pexelsWasharapolDBinyoJundang2731667Jpg.jpg"; // plasmic-import: -qtUVHAbg/picture
import image9EiY5D9FRe5 from "./images/image9.jpg"; // plasmic-import: eiY5-D9fRe5/picture
import image10HOvMEtfWrmh from "./images/image10.jpg"; // plasmic-import: hOvMEtfWrmh/picture
import image11FCbt8Jwzttd from "./images/image11.jpg"; // plasmic-import: fCbt8Jwzttd/picture
import image12BOu6HVJejY0 from "./images/image12.jpg"; // plasmic-import: bOU6hVJejY0/picture
import image131OzKv2WggqS from "./images/image13.jpg"; // plasmic-import: 1ozKV2wggqS/picture

export const PlasmicBlogOverview__VariantProps = new Array();

export const PlasmicBlogOverview__ArgProps = new Array();

const __wrapUserFunction =
  globalThis.__PlasmicWrapUserFunction ?? ((loc, fn) => fn());

const __wrapUserPromise =
  globalThis.__PlasmicWrapUserPromise ??
  (async (loc, promise) => {
    return await promise;
  });

function PlasmicBlogOverview__RenderFunc(props) {
  const { variants, overrides, forNode } = props;
  const $ctx = ph.useDataEnv?.() || {};
  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);
  const $props = {
    ...args,
    ...variants
  };
  const refsRef = React.useRef({});
  const $refs = refsRef.current;
  const currentUser = p.useCurrentUser?.() || {};
  const [$queries, setDollarQueries] = React.useState({});
  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariantstvKzUvB7Ggzh0()
  });
  return (
    <React.Fragment>
      <div className={projectcss.plasmic_page_wrapper}>
        <p.Stack
          as={"div"}
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          hasGap={true}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            plasmic_antd_5_hostless_css.plasmic_tokens,
            sty.root
          )}
        >
          <div className={classNames(projectcss.all, sty.freeBox__ovIlq)}>
            <Navbar
              data-plasmic-name={"navbar"}
              data-plasmic-override={overrides.navbar}
              className={classNames("__wab_instance", sty.navbar)}
            />
          </div>
          <div className={classNames(projectcss.all, sty.freeBox__g5OLm)}>
            <div
              data-plasmic-name={"pageBanner"}
              data-plasmic-override={overrides.pageBanner}
              className={classNames(projectcss.all, sty.pageBanner)}
            >
              <div className={classNames(projectcss.all, sty.freeBox__n1B81)}>
                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.columns__cgSCx)}
                >
                  <div
                    className={classNames(projectcss.all, sty.column___6OfUa)}
                  >
                    <p.Stack
                      as={"div"}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.freeBox__lcyU9)}
                    >
                      <h1
                        data-plasmic-name={"h1"}
                        data-plasmic-override={overrides.h1}
                        className={classNames(
                          projectcss.all,
                          projectcss.h1,
                          projectcss.__wab_text,
                          sty.h1
                        )}
                      >
                        {"Blog"}
                      </h1>
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text___7NozS
                        )}
                      >
                        {
                          "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,"
                        }
                      </div>
                    </p.Stack>
                  </div>
                  <div
                    className={classNames(projectcss.all, sty.column__ch22H)}
                  >
                    <p.PlasmicImg
                      alt={""}
                      className={classNames(sty.img__pLzpO)}
                      displayHeight={"auto"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={
                        hasVariant(globalVariants, "screen", "mobileOnly")
                          ? "100%"
                          : "100%"
                      }
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"auto"}
                      loading={
                        hasVariant(globalVariants, "screen", "mobileOnly")
                          ? "lazy"
                          : "lazy"
                      }
                      src={
                        hasVariant(globalVariants, "screen", "mobileOnly")
                          ? {
                              src: image7YoXd0XTyBq,
                              fullWidth: 1920,
                              fullHeight: 1280,
                              aspectRatio: undefined
                            }
                          : {
                              src: image7YoXd0XTyBq,
                              fullWidth: 1920,
                              fullHeight: 1280,
                              aspectRatio: undefined
                            }
                      }
                    />
                  </div>
                </p.Stack>
              </div>
            </div>
            <div className={classNames(projectcss.all, sty.freeBox__zjBua)}>
              <div className={classNames(projectcss.all, sty.freeBox__ckYGu)}>
                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.columns___55KpF)}
                >
                  <div
                    className={classNames(projectcss.all, sty.column__nIieu)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        sty.columns___2SYqf
                      )}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.column__xtNDg
                        )}
                      >
                        <p.PlasmicImg
                          alt={""}
                          className={classNames(sty.img__ctTtn)}
                          displayHeight={"100%"}
                          displayMaxHeight={"none"}
                          displayMaxWidth={"100%"}
                          displayMinHeight={"0"}
                          displayMinWidth={"0"}
                          displayWidth={"100%"}
                          loading={"lazy"}
                          src={{
                            src: pexelsWasharapolDBinyoJundang2731667JpgQtUvhAbg,
                            fullWidth: 3840,
                            fullHeight: 2560,
                            aspectRatio: undefined
                          }}
                        />
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.column__hazWq
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__bgapI
                          )}
                        >
                          <h4
                            className={classNames(
                              projectcss.all,
                              projectcss.h4,
                              projectcss.__wab_text,
                              sty.h4__vgW3L
                            )}
                          >
                            {hasVariant(globalVariants, "screen", "mobileOnly")
                              ? "Customer Loyalty Programs That Stick"
                              : "Founders diary"}
                          </h4>
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__ndqi
                            )}
                          >
                            {
                              "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor ..."
                            }
                          </div>
                          <Button2
                            className={classNames(
                              "__wab_instance",
                              sty.button2__ncWi
                            )}
                            color={"blue"}
                            endIcon={
                              <Icon6Icon
                                className={classNames(
                                  projectcss.all,
                                  sty.svg__b04Jl
                                )}
                                role={"img"}
                              />
                            }
                            shape={"rounded"}
                            showEndIcon={true}
                            startIcon={
                              <ChecksvgIcon
                                className={classNames(
                                  projectcss.all,
                                  sty.svg__oytbx
                                )}
                                role={"img"}
                              />
                            }
                            submitsForm={true}
                          >
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__fIRf8
                              )}
                            >
                              {"Read post"}
                            </div>
                          </Button2>
                        </div>
                      </div>
                    </div>
                  </div>
                  <div
                    className={classNames(projectcss.all, sty.column__tiUt6)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.columns__ytCnU)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.column___5Broz
                        )}
                      >
                        <p.PlasmicImg
                          alt={""}
                          className={classNames(sty.img__xSxyv)}
                          displayHeight={"100%"}
                          displayMaxHeight={"none"}
                          displayMaxWidth={"100%"}
                          displayMinHeight={"0"}
                          displayMinWidth={"0"}
                          displayWidth={"100%"}
                          loading={"lazy"}
                          src={{
                            src: image9EiY5D9FRe5,
                            fullWidth: 1920,
                            fullHeight: 1280,
                            aspectRatio: undefined
                          }}
                        />
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.column__zfyMa
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox___9P1YD
                          )}
                        >
                          <h4
                            className={classNames(
                              projectcss.all,
                              projectcss.h4,
                              projectcss.__wab_text,
                              sty.h4__hzyik
                            )}
                          >
                            {hasVariant(globalVariants, "screen", "mobileOnly")
                              ? "Customer Loyalty Programs That Stick"
                              : "Blog heading dummy"}
                          </h4>
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__yGgxv
                            )}
                          >
                            {
                              "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor ..."
                            }
                          </div>
                          <Button2
                            className={classNames(
                              "__wab_instance",
                              sty.button2__d9Hiy
                            )}
                            color={"blue"}
                            endIcon={
                              <Icon6Icon
                                className={classNames(
                                  projectcss.all,
                                  sty.svg__wPp7K
                                )}
                                role={"img"}
                              />
                            }
                            shape={"rounded"}
                            showEndIcon={true}
                            startIcon={
                              <ChecksvgIcon
                                className={classNames(
                                  projectcss.all,
                                  sty.svg__lw1W
                                )}
                                role={"img"}
                              />
                            }
                            submitsForm={true}
                          >
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__tkdNm
                              )}
                            >
                              {"Learn more"}
                            </div>
                          </Button2>
                        </div>
                      </div>
                    </div>
                  </div>
                  <div
                    className={classNames(projectcss.all, sty.column__znfLu)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.columns__rZbbu)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.column__emjxn
                        )}
                      >
                        <p.PlasmicImg
                          alt={""}
                          className={classNames(sty.img__jk0Bm)}
                          displayHeight={"100%"}
                          displayMaxHeight={"none"}
                          displayMaxWidth={"100%"}
                          displayMinHeight={"0"}
                          displayMinWidth={"0"}
                          displayWidth={"100%"}
                          loading={"lazy"}
                          src={{
                            src: image10HOvMEtfWrmh,
                            fullWidth: 1920,
                            fullHeight: 1080,
                            aspectRatio: undefined
                          }}
                        />
                      </div>
                      <div
                        className={classNames(projectcss.all, sty.column__rqUn)}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__rcsg2
                          )}
                        >
                          <h4
                            className={classNames(
                              projectcss.all,
                              projectcss.h4,
                              projectcss.__wab_text,
                              sty.h4__dVb9W
                            )}
                          >
                            {hasVariant(globalVariants, "screen", "mobileOnly")
                              ? "Customer Loyalty Programs That Stick"
                              : "Blog heading dummy"}
                          </h4>
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__bjyOr
                            )}
                          >
                            {
                              "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor ..."
                            }
                          </div>
                          <Button2
                            className={classNames(
                              "__wab_instance",
                              sty.button2__zhqmJ
                            )}
                            color={"blue"}
                            endIcon={
                              <Icon6Icon
                                className={classNames(
                                  projectcss.all,
                                  sty.svg__eRb4S
                                )}
                                role={"img"}
                              />
                            }
                            shape={"rounded"}
                            showEndIcon={true}
                            startIcon={
                              <ChecksvgIcon
                                className={classNames(
                                  projectcss.all,
                                  sty.svg__wIkMl
                                )}
                                role={"img"}
                              />
                            }
                            submitsForm={true}
                          >
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__dbVym
                              )}
                            >
                              {"Learn more"}
                            </div>
                          </Button2>
                        </div>
                      </div>
                    </div>
                  </div>
                  <div
                    className={classNames(projectcss.all, sty.column__lqKIq)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.columns__haMtF)}
                    >
                      <div
                        className={classNames(projectcss.all, sty.column__fdWb)}
                      >
                        <p.PlasmicImg
                          alt={""}
                          className={classNames(sty.img__dhIsK)}
                          displayHeight={"100%"}
                          displayMaxHeight={"none"}
                          displayMaxWidth={"100%"}
                          displayMinHeight={"0"}
                          displayMinWidth={"0"}
                          displayWidth={"100%"}
                          loading={"lazy"}
                          src={{
                            src: image11FCbt8Jwzttd,
                            fullWidth: 640,
                            fullHeight: 360,
                            aspectRatio: undefined
                          }}
                        />
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.column__rudIw
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__r7Ri5
                          )}
                        >
                          <h4
                            className={classNames(
                              projectcss.all,
                              projectcss.h4,
                              projectcss.__wab_text,
                              sty.h4__btQo6
                            )}
                          >
                            {hasVariant(globalVariants, "screen", "mobileOnly")
                              ? "Customer Loyalty Programs That Stick"
                              : "Blog heading dummy"}
                          </h4>
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__ciQub
                            )}
                          >
                            {
                              "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor ..."
                            }
                          </div>
                          <Button2
                            className={classNames(
                              "__wab_instance",
                              sty.button2___150Do
                            )}
                            color={"blue"}
                            endIcon={
                              <Icon6Icon
                                className={classNames(
                                  projectcss.all,
                                  sty.svg___5VKol
                                )}
                                role={"img"}
                              />
                            }
                            shape={"rounded"}
                            showEndIcon={true}
                            startIcon={
                              <ChecksvgIcon
                                className={classNames(
                                  projectcss.all,
                                  sty.svg__d9Wos
                                )}
                                role={"img"}
                              />
                            }
                            submitsForm={true}
                          >
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__hYpku
                              )}
                            >
                              {"Learn more"}
                            </div>
                          </Button2>
                        </div>
                      </div>
                    </div>
                  </div>
                  <div className={classNames(projectcss.all, sty.column__uyN)}>
                    <div
                      className={classNames(projectcss.all, sty.columns__cIjSj)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.column__ec3Id
                        )}
                      >
                        <p.PlasmicImg
                          alt={""}
                          className={classNames(sty.img__iZoB)}
                          displayHeight={"100%"}
                          displayMaxHeight={"none"}
                          displayMaxWidth={"100%"}
                          displayMinHeight={"0"}
                          displayMinWidth={"0"}
                          displayWidth={"100%"}
                          loading={"lazy"}
                          src={{
                            src: image12BOu6HVJejY0,
                            fullWidth: 1920,
                            fullHeight: 1280,
                            aspectRatio: undefined
                          }}
                        />
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.column___06Hmi
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__kbbj8
                          )}
                        >
                          <h4
                            className={classNames(
                              projectcss.all,
                              projectcss.h4,
                              projectcss.__wab_text,
                              sty.h4___2K6I3
                            )}
                          >
                            {hasVariant(globalVariants, "screen", "mobileOnly")
                              ? "Customer Loyalty Programs That Stick"
                              : "Blog heading dummy"}
                          </h4>
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text___107Ck
                            )}
                          >
                            {
                              "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor ..."
                            }
                          </div>
                          <Button2
                            className={classNames(
                              "__wab_instance",
                              sty.button2__z4Ujh
                            )}
                            color={"blue"}
                            endIcon={
                              <Icon6Icon
                                className={classNames(
                                  projectcss.all,
                                  sty.svg__cvHhq
                                )}
                                role={"img"}
                              />
                            }
                            shape={"rounded"}
                            showEndIcon={true}
                            startIcon={
                              <ChecksvgIcon
                                className={classNames(
                                  projectcss.all,
                                  sty.svg__ivG8F
                                )}
                                role={"img"}
                              />
                            }
                            submitsForm={true}
                          >
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__inYCs
                              )}
                            >
                              {"Learn more"}
                            </div>
                          </Button2>
                        </div>
                      </div>
                    </div>
                  </div>
                  <div
                    className={classNames(projectcss.all, sty.column__k512Y)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.columns__tTmu)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.column__lPJnY
                        )}
                      >
                        <p.PlasmicImg
                          alt={""}
                          className={classNames(sty.img__zgVcq)}
                          displayHeight={"100%"}
                          displayMaxHeight={"none"}
                          displayMaxWidth={"100%"}
                          displayMinHeight={"0"}
                          displayMinWidth={"0"}
                          displayWidth={"100%"}
                          loading={"lazy"}
                          src={{
                            src: image131OzKv2WggqS,
                            fullWidth: 1920,
                            fullHeight: 1280,
                            aspectRatio: undefined
                          }}
                        />
                      </div>
                      <div
                        className={classNames(projectcss.all, sty.column__pgFb)}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__y4Xrg
                          )}
                        >
                          <h4
                            className={classNames(
                              projectcss.all,
                              projectcss.h4,
                              projectcss.__wab_text,
                              sty.h4__gcO9S
                            )}
                          >
                            {hasVariant(globalVariants, "screen", "mobileOnly")
                              ? "Customer Loyalty Programs That Stick"
                              : "Blog heading dummy"}
                          </h4>
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__aWgh
                            )}
                          >
                            {
                              "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor ..."
                            }
                          </div>
                          <Button2
                            className={classNames(
                              "__wab_instance",
                              sty.button2__xD8IR
                            )}
                            color={"blue"}
                            endIcon={
                              <Icon6Icon
                                className={classNames(
                                  projectcss.all,
                                  sty.svg__wyDav
                                )}
                                role={"img"}
                              />
                            }
                            shape={"rounded"}
                            showEndIcon={true}
                            startIcon={
                              <ChecksvgIcon
                                className={classNames(
                                  projectcss.all,
                                  sty.svg___02DiV
                                )}
                                role={"img"}
                              />
                            }
                            submitsForm={true}
                          >
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__nScMi
                              )}
                            >
                              {"Learn more"}
                            </div>
                          </Button2>
                        </div>
                      </div>
                    </div>
                  </div>
                  <div
                    className={classNames(projectcss.all, sty.column__lfJ8G)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.columns__qnoVl)}
                    >
                      <div
                        className={classNames(projectcss.all, sty.column__dYlw)}
                      >
                        <p.PlasmicImg
                          alt={""}
                          className={classNames(sty.img__fd5YX)}
                          displayHeight={"100%"}
                          displayMaxHeight={"none"}
                          displayMaxWidth={"100%"}
                          displayMinHeight={"0"}
                          displayMinWidth={"0"}
                          displayWidth={"100%"}
                          loading={"lazy"}
                          src={{
                            src: image7YoXd0XTyBq,
                            fullWidth: 1920,
                            fullHeight: 1280,
                            aspectRatio: undefined
                          }}
                        />
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.column__gwoDo
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__anYkj
                          )}
                        >
                          <h4
                            className={classNames(
                              projectcss.all,
                              projectcss.h4,
                              projectcss.__wab_text,
                              sty.h4__qZd1N
                            )}
                          >
                            {hasVariant(globalVariants, "screen", "mobileOnly")
                              ? "Customer Loyalty Programs That Stick"
                              : "Blog heading dummy"}
                          </h4>
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__wk2ND
                            )}
                          >
                            {
                              "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor ..."
                            }
                          </div>
                          <Button2
                            className={classNames(
                              "__wab_instance",
                              sty.button2__xea1L
                            )}
                            color={"blue"}
                            endIcon={
                              <Icon6Icon
                                className={classNames(
                                  projectcss.all,
                                  sty.svg__wmMj7
                                )}
                                role={"img"}
                              />
                            }
                            shape={"rounded"}
                            showEndIcon={true}
                            startIcon={
                              <ChecksvgIcon
                                className={classNames(
                                  projectcss.all,
                                  sty.svg__yhdbQ
                                )}
                                role={"img"}
                              />
                            }
                            submitsForm={true}
                          >
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__gr0I
                              )}
                            >
                              {"Learn more"}
                            </div>
                          </Button2>
                        </div>
                      </div>
                    </div>
                  </div>
                  <div
                    className={classNames(projectcss.all, sty.column__a68Yv)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.columns__gpeYc)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.column___0GeLj
                        )}
                      >
                        <p.PlasmicImg
                          alt={""}
                          className={classNames(sty.img___3OkqY)}
                          displayHeight={"100%"}
                          displayMaxHeight={"none"}
                          displayMaxWidth={"100%"}
                          displayMinHeight={"0"}
                          displayMinWidth={"0"}
                          displayWidth={"100%"}
                          loading={"lazy"}
                          src={{
                            src: image7YoXd0XTyBq,
                            fullWidth: 1920,
                            fullHeight: 1280,
                            aspectRatio: undefined
                          }}
                        />
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.column__dokn6
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__vcMon
                          )}
                        >
                          <h4
                            className={classNames(
                              projectcss.all,
                              projectcss.h4,
                              projectcss.__wab_text,
                              sty.h4__uf9DH
                            )}
                          >
                            {hasVariant(globalVariants, "screen", "mobileOnly")
                              ? "Customer Loyalty Programs That Stick"
                              : "Blog heading dummy"}
                          </h4>
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__jqtDs
                            )}
                          >
                            {
                              "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor ..."
                            }
                          </div>
                          <Button2
                            className={classNames(
                              "__wab_instance",
                              sty.button2__ejXmP
                            )}
                            color={"blue"}
                            endIcon={
                              <Icon6Icon
                                className={classNames(
                                  projectcss.all,
                                  sty.svg__zp5Ws
                                )}
                                role={"img"}
                              />
                            }
                            shape={"rounded"}
                            showEndIcon={true}
                            startIcon={
                              <ChecksvgIcon
                                className={classNames(
                                  projectcss.all,
                                  sty.svg__oqUqY
                                )}
                                role={"img"}
                              />
                            }
                            submitsForm={true}
                          >
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__hXaY
                              )}
                            >
                              {"Learn more"}
                            </div>
                          </Button2>
                        </div>
                      </div>
                    </div>
                  </div>
                </p.Stack>
              </div>
            </div>
            <Footer
              data-plasmic-name={"footer"}
              data-plasmic-override={overrides.footer}
              className={classNames("__wab_instance", sty.footer)}
            />
          </div>
        </p.Stack>
      </div>
    </React.Fragment>
  );
}

const PlasmicDescendants = {
  root: ["root", "navbar", "pageBanner", "h1", "footer"],
  navbar: ["navbar"],
  pageBanner: ["pageBanner", "h1"],
  h1: ["h1"],
  footer: ["footer"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicBlogOverview__ArgProps,
          internalVariantPropNames: PlasmicBlogOverview__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicBlogOverview__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicBlogOverview";
  } else {
    func.displayName = `PlasmicBlogOverview.${nodeName}`;
  }
  return func;
}

export const PlasmicBlogOverview = Object.assign(
  // Top-level PlasmicBlogOverview renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    navbar: makeNodeComponent("navbar"),
    pageBanner: makeNodeComponent("pageBanner"),
    h1: makeNodeComponent("h1"),
    footer: makeNodeComponent("footer"),
    // Metadata about props expected for PlasmicBlogOverview
    internalVariantProps: PlasmicBlogOverview__VariantProps,
    internalArgProps: PlasmicBlogOverview__ArgProps,
    // Page metadata
    pageMetadata: {
      title: "",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicBlogOverview;
/* prettier-ignore-end */
