// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: qYXJkyifyxfQuqtTDFQCRa
// Component: tawyW2Li6P
import * as React from "react";
import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/react-web/lib/host";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import { AntdInputNumber } from "@plasmicpkgs/antd5/skinny/registerInput"; // plasmic-import: wxD5qjEe3pU/codeComponent
import "@plasmicapp/react-web/lib/plasmic.css";
import plasmic_antd_5_hostless_css from "../antd_5_hostless/plasmic_antd_5_hostless.module.css"; // plasmic-import: ohDidvG9XsCeFumugENU3J/projectcss
import projectcss from "./plasmic_tiny_garden_solutions.module.css"; // plasmic-import: qYXJkyifyxfQuqtTDFQCRa/projectcss
import sty from "./PlasmicGetalVraag.module.css"; // plasmic-import: tawyW2Li6P/css

export const PlasmicGetalVraag__VariantProps = new Array();

export const PlasmicGetalVraag__ArgProps = new Array();

const __wrapUserFunction =
  globalThis.__PlasmicWrapUserFunction ?? ((loc, fn) => fn());

const __wrapUserPromise =
  globalThis.__PlasmicWrapUserPromise ??
  (async (loc, promise) => {
    return await promise;
  });

function PlasmicGetalVraag__RenderFunc(props) {
  const { variants, overrides, forNode } = props;
  const $ctx = ph.useDataEnv?.() || {};
  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);
  const $props = {
    ...args,
    ...variants
  };
  const refsRef = React.useRef({});
  const $refs = refsRef.current;
  const currentUser = p.useCurrentUser?.() || {};
  const [$queries, setDollarQueries] = React.useState({});
  const stateSpecs = React.useMemo(
    () => [
      {
        path: "numberInput.value",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $ctx }) => undefined
      }
    ],

    [$props, $ctx]
  );
  const $state = p.useDollarState(stateSpecs, { $props, $ctx, $queries });
  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        plasmic_antd_5_hostless_css.plasmic_tokens,
        sty.root
      )}
    >
      <div className={classNames(projectcss.all, sty.freeBox__tGveT)}>
        <div className={classNames(projectcss.all, sty.freeBox__gpaS6)}>
          <h1
            data-plasmic-name={"h1"}
            data-plasmic-override={overrides.h1}
            className={classNames(
              projectcss.all,
              projectcss.h1,
              projectcss.__wab_text,
              sty.h1
            )}
          >
            {"How many times  a week do you smoke weed?"}
          </h1>
          <div className={classNames(projectcss.all, sty.freeBox___7CjtU)} />
        </div>
        <div className={classNames(projectcss.all, sty.freeBox__bazPt)}>
          <AntdInputNumber
            data-plasmic-name={"numberInput"}
            data-plasmic-override={overrides.numberInput}
            className={classNames("__wab_instance", sty.numberInput)}
            onChange={p.generateStateOnChangeProp($state, [
              "numberInput",
              "value"
            ])}
            value={p.generateStateValueProp($state, ["numberInput", "value"])}
          />
        </div>
      </div>
    </div>
  );
}

const PlasmicDescendants = {
  root: ["root", "h1", "numberInput"],
  h1: ["h1"],
  numberInput: ["numberInput"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicGetalVraag__ArgProps,
          internalVariantPropNames: PlasmicGetalVraag__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicGetalVraag__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicGetalVraag";
  } else {
    func.displayName = `PlasmicGetalVraag.${nodeName}`;
  }
  return func;
}

export const PlasmicGetalVraag = Object.assign(
  // Top-level PlasmicGetalVraag renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    h1: makeNodeComponent("h1"),
    numberInput: makeNodeComponent("numberInput"),
    // Metadata about props expected for PlasmicGetalVraag
    internalVariantProps: PlasmicGetalVraag__VariantProps,
    internalArgProps: PlasmicGetalVraag__ArgProps
  }
);

export default PlasmicGetalVraag;
/* prettier-ignore-end */
